const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {Service}=require('../desktop/service.cjs');
const {Speech,CLOUD_MODEL,BASE}=require('../desktop/speech.cjs');
const {createSecrets}=require('../desktop/secrets.cjs');
function wav(seconds=10,rate=24000){const b=Buffer.alloc(44+seconds*rate*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(b.length-44,40);return b;}
function fixture(t,options={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'sayagain-speech-'));const service=new Service(path.join(root,'data'));let key='';const secrets={has:()=>!!key,get:()=>key,set:v=>{key=v;},clear:()=>{key='';}};const speech=new Speech(service,root,{secrets,localStatus:()=>({space_ok:false,installed:false,reason:'磁盘空间不足'}),...options});t.after(async()=>{await speech.close();service.close();fs.rmSync(root,{recursive:true,force:true});});service.saveSettings({revision:service.config().body.revision,native_language:'zh-CN',target_language:'en-US'});const expression=service.addExpression({original:'I very like it.',improved:'I really like it.',explanation:'测试'});const voice=service.saveVoice({name:'模拟声音',note:'仅测试'});service.addSample({voice_id:voice.block_id,language:'en-US',transcript:'Test sample',bytes:wav(),media_type:'audio/wav',duration_ms:10000,waveform:Array(64).fill(0),source:'import'});return{root,service,speech,secrets,input:{expression_id:expression.block_id,voice_id:voice.block_id,cloud_consent:true}};}
async function finish(speech){await new Promise(resolve=>setImmediate(resolve));await speech.drain();while(speech.busy)await new Promise(resolve=>setTimeout(resolve,5));}

test('queue exposes execution order, timestamps and cancellation without running cancelled items',async t=>{
 const calls=[];let release;
 const {speech,service,input}=fixture(t,{localStatus:()=>({installed:true,space_ok:true,runtime:{model_id:'test',revision:'test',model_path:'unused',python:'unused'}}),localRunner:async request=>{calls.push(request.text);if(calls.length===1)await new Promise(resolve=>{release=resolve;});fs.writeFileSync(request.output_path,wav(1));}});
 const first=speech.request(input);await new Promise(resolve=>setImmediate(resolve));
 try{
  const add=text=>{const e=service.addExpression({original:text,improved:text,explanation:'测试'});return speech.request({...input,expression_id:e.block_id});};
  const second=add('Second sentence.'),third=add('Third sentence.');
  assert.deepEqual(service.state().synthesis_queue,[second.block_id,third.block_id]);
  assert(service.store.get(first.block_id).body.started_at>=first.body.queued_at);
  speech.cancel({id:second.block_id});assert.deepEqual(service.state().synthesis_queue,[third.block_id]);
  assert(service.store.get(second.block_id).body.completed_at);
 }finally{release();}
 await finish(speech);assert.deepEqual(calls,['I really like it.','Third sentence.']);
 assert.equal(service.state().synthesis_queue.length,0);
 assert(service.store.get(first.block_id).body.completed_at>=service.store.get(first.block_id).body.started_at);
});
test('insufficient disk blocks local work; cloud needs explicit enable and per-generation consent',async t=>{let calls=0;const {speech,input}=fixture(t,{fetch:async()=>{calls++;throw Error('unexpected');}});assert.throws(()=>speech.request(input),/空间不足/);assert.throws(()=>speech.configure({mode:'cloud',cloud_enabled:false,api_key:'test-key'}),/主动/);assert.equal(speech.status().has_api_key,false);speech.configure({mode:'cloud',cloud_enabled:true,api_key:'test-key'});assert.throws(()=>speech.request({...input,cloud_consent:false}),/确认/);assert.equal(calls,0);assert(!JSON.stringify(speech.status()).includes('test-key'));});
test('cloud enrollment, matching model, saved audio, reuse and no credentials on audio download',async t=>{const calls=[];const {speech,service,input}=fixture(t,{fetch:async(url,options)=>{calls.push({url,options});if(url.endsWith('/customization'))return Response.json({output:{voice:'fake-voice'}});if(url.endsWith('/generation'))return Response.json({output:{audio:{url:'http://test.aliyuncs.com/audio.wav?Signature=a%2Bb%3D&Expires=123'}}});return new Response(wav(1));}});speech.configure({mode:'cloud',cloud_enabled:true,api_key:'test-only-key'});const result=speech.request(input);await finish(speech);const saved=service.store.get(result.block_id);assert.equal(saved.body.status,'succeeded');assert(fs.existsSync(service.asset(saved.body.asset_id).filename));assert.equal(calls.length,3);assert.equal(calls[0].url,BASE+'/services/audio/tts/customization');assert.equal(JSON.parse(calls[0].options.body).input.target_model,CLOUD_MODEL);assert.equal(JSON.parse(calls[1].options.body).model,CLOUD_MODEL);assert.equal(calls[2].options.headers,undefined);assert.equal(calls[2].url,'https://test.aliyuncs.com/audio.wav?Signature=a%2Bb%3D&Expires=123');assert.equal(speech.request(input).cached,true);assert.equal(calls.length,3);const e=service.addExpression({original:'Explain me.',improved:'Please explain this to me.',explanation:'测试'});speech.request({...input,expression_id:e.block_id});await finish(speech);assert.equal(calls.filter(c=>c.url.endsWith('/customization')).length,1);assert.equal(calls.length,5);});
test('provider failure never becomes success and does not persist response secrets',async t=>{const {speech,service,input}=fixture(t,{fetch:async()=>new Response('private provider response test-only-key',{status:401})});speech.configure({mode:'cloud',cloud_enabled:true,api_key:'test-only-key'});const result=speech.request(input);await finish(speech);assert.equal(service.store.get(result.block_id).body.status,'failed');assert.match(service.store.get(result.block_id).body.error,/401/);assert(!JSON.stringify(service.state()).includes('test-only-key'));});
test('removing key cancels queued cloud work without network request',async t=>{let calls=0;const {speech,service,input}=fixture(t,{fetch:async()=>{calls++;throw Error('unexpected');}});speech.configure({mode:'cloud',cloud_enabled:true,api_key:'test-only-key'});const result=speech.request(input);speech.clearKey();await finish(speech);assert.equal(service.store.get(result.block_id).body.status,'cancelled');assert.equal(calls,0);assert.equal(speech.status().has_api_key,false);});
test('plaintext key persists and reopens without keychain; permissions and clear',t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'sayagain-plain-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const secrets=createSecrets(root),file=path.join(root,'qianwen-api-keys.secret');secrets.set('test-only-plaintext-key');assert.equal(JSON.parse(fs.readFileSync(file,'utf8')).keys[0].key,'test-only-plaintext-key');if(process.platform!=='win32')assert.equal(fs.statSync(file).mode&0o777,0o600); // Windows uses inherited ACLs, not POSIX mode bits.
assert.equal(createSecrets(root).get(),'test-only-plaintext-key');assert.equal(secrets.status().usable,true);assert.throws(()=>secrets.set('bad key'),/空格/);assert.equal(secrets.get(),'test-only-plaintext-key');secrets.clear();assert.equal(secrets.status().present,false);});
test('legacy ciphertext can be replaced without decryption; status does not disclose keys',t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'sayagain-legacy-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const legacy=path.join(root,'qianwen-api-key.enc');fs.writeFileSync(legacy,'unreadable-ciphertext');const secrets=createSecrets(root);assert.equal(secrets.has(),false);assert.match(secrets.status().error,/重新粘贴/);assert.throws(()=>secrets.get(),/重新粘贴/);secrets.set('replacement-test-key');assert.equal(secrets.get(),'replacement-test-key');assert(!JSON.stringify(secrets.status()).includes('replacement-test-key'));secrets.clear();assert.equal(fs.existsSync(legacy),false);});

test('normalize copied key wrappers without joining multiple credentials',()=>{const {normalizeKey}=require('../desktop/secrets.cjs');for(const value of ['  test-key  ','Bearer test-key','API Key: "test-key"','AK：test-key','\u200btest-key\ufeff'])assert.equal(normalizeKey(value),'test-key');assert.equal(normalizeKey('abc'),'abc');assert.throws(()=>normalizeKey('key-one\nkey-two'),/一个完整 Key/);assert.throws(()=>normalizeKey('test-key 应用名称'),/应用名称/);assert.throws(()=>normalizeKey('key\u200bvalue'),/不可见/);assert.throws(()=>normalizeKey('  '),/为空/);});

test('multiple keys persist with names and active choice; old key survives migration; deleting does not resurrect it',t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'sayagain-key-list-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fs.writeFileSync(path.join(root,'qianwen-api-key.secret'),'original-test-key');const secrets=createSecrets(root),value=secrets.list();assert.equal(value.keys[0].key,'original-test-key');value.keys.push({id:'second',name:'工作',key:'second-test-key'});value.active_id='second';secrets.save(value);const reopened=createSecrets(root);assert.equal(reopened.get(),'second-test-key');assert.equal(reopened.list().keys.length,2);assert.equal(reopened.list().keys[1].name,'工作');assert.throws(()=>reopened.save({...value,active_id:'missing'}),/请选择/);assert.equal(reopened.get(),'second-test-key');assert.throws(()=>reopened.save({...value,keys:[...value.keys,{id:'third',key:'second-test-key'}]}),/重复/);reopened.save({keys:[value.keys[0]],active_id:'legacy'});assert.equal(reopened.get(),'original-test-key');reopened.save({keys:[],active_id:null});assert.equal(createSecrets(root).has(),false);assert.equal(createSecrets(root).list().keys.length,0);});

test('audio URLs accept official HTTP OSS results without changing signature; reject other destinations',()=>{const {normalizeAudioUrl}=require('../desktop/audio-url.cjs');assert.equal(normalizeAudioUrl('http://dashscope-result-bj.oss-cn-beijing.aliyuncs.com/a.wav?Signature=a%2Fb%2B%3D'),'https://dashscope-result-bj.oss-cn-beijing.aliyuncs.com/a.wav?Signature=a%2Fb%2B%3D');for(const url of ['https://aliyuncs.com.evil.test/a','http://127.0.0.1/a','file:///tmp/a','https://user:password@test.aliyuncs.com/a','https://test.aliyuncs.com:8443/a'])assert.throws(()=>normalizeAudioUrl(url),/不支持/);assert.throws(()=>normalizeAudioUrl(undefined),/有效/);});
test('normalize streaming WAV sizes without altering PCM; real truncation still fails',()=>{const {parseWav,normalizeCloudWav}=require('../desktop/audio.cjs');for(const sentinel of [0xffffffff,0xfffffffe,0x7fffffff]){const raw=wav(1);raw.writeUInt32LE(sentinel,4);raw.writeUInt32LE(sentinel,40);assert.throws(()=>parseWav(raw),/不完整/);const fixed=normalizeCloudWav(raw);assert.equal(parseWav(fixed).duration_ms,1000);assert.deepEqual(fixed.subarray(44),raw.subarray(44));assert.equal(fixed.readUInt32LE(4),fixed.length-8);assert.equal(fixed.readUInt32LE(40),fixed.length-44);}assert.throws(()=>normalizeCloudWav(wav(1).subarray(0,-100)),/不完整/);const malformed=wav(1);malformed.writeUInt32LE(0xffffffff,40);assert.throws(()=>normalizeCloudWav(malformed.subarray(0,-1)),/完整/);});
test('cloud parse failure retains download and retry never resynthesizes',async t=>{let calls=0;const{root,speech,service,input}=fixture(t,{fetch:async url=>{calls++;if(url.endsWith('/customization'))return Response.json({output:{voice:'fake-voice'}});if(url.endsWith('/generation'))return Response.json({output:{audio:{url:'https://test.aliyuncs.com/a.wav'}}});return new Response(wav(1).subarray(0,-100));}});speech.configure({mode:'cloud',cloud_enabled:true,api_key:'test-key'});const result=speech.request(input);await finish(speech);assert.equal(service.store.get(result.block_id).body.status,'failed');assert.equal(calls,3);const file=path.join(root,'tts-downloads',result.block_id+'.wav');assert(fs.existsSync(file));speech.request(input);await finish(speech);assert.equal(calls,3);fs.writeFileSync(file,wav(1));speech.request(input);await finish(speech);assert.equal(service.store.get(result.block_id).body.status,'succeeded');assert.equal(calls,3);assert.equal(fs.existsSync(file),false);});

for(const model of require('../desktop/cloud-models.cjs').CLOUD_MODELS.filter(m=>['qwen-audio','cosyvoice'].includes(m.family)))test(`model selection and upload/enrollment/synthesis: ${model.id}`,async t=>{
 const calls=[];const{speech,service,input}=fixture(t,{fetch:async(url,options)=>{calls.push({url,options});if(url.includes('getPolicy'))return Response.json({data:{upload_dir:'tests',upload_host:'https://test.aliyuncs.com/',oss_access_key_id:'upload-id',signature:'signature',policy:'policy',x_oss_object_acl:'private',x_oss_forbid_overwrite:'true'}});if(options.body instanceof FormData){assert.equal(options.headers,undefined);assert.equal(options.body.get('file').type,'audio/wav');return new Response('');}if(url.endsWith('/customization')){const payload=JSON.parse(options.body);assert.equal(payload.model,'voice-enrollment');assert.equal(payload.input.action,'create_voice');assert.equal(payload.input.target_model,model.id);assert.match(payload.input.url,/^oss:\/\/tests\//);assert.equal(options.headers['X-DashScope-OssResourceResolve'],'enable');return Response.json({output:{voice_id:'voice-'+model.id}});}if(url.endsWith('/SpeechSynthesizer')){const payload=JSON.parse(options.body);assert.equal(payload.model,model.id);assert.equal(payload.input.voice,'voice-'+model.id);assert.equal(payload.input.format,'wav');return Response.json({output:{audio:{url:'https://test.aliyuncs.com/result.wav'}}});}return new Response(wav(1));}});
 speech.configure({mode:'cloud',cloud_enabled:true,api_key:'test-key',cloud_model:model.id});assert.equal(speech.status().cloud_model,model.id);
 const result=speech.request(input);speech.configure({mode:'cloud',cloud_enabled:true,cloud_model:CLOUD_MODEL});await finish(speech);assert.equal(service.store.get(result.block_id).body.status,'succeeded');assert.equal(service.store.get(result.block_id).body.model_id,model.id);assert.equal(speech.request({...input,model_id:model.id}).cached,true);assert.equal(speech.status().cloud_model,CLOUD_MODEL);assert.equal(calls.length,5);
 const e=service.addExpression({original:'Again.',improved:'Please say that again.',explanation:'测试'});speech.request({...input,expression_id:e.block_id,model_id:model.id});await finish(speech);assert.equal(calls.length,7);assert.equal(calls.filter(c=>c.url.endsWith('/customization')).length,1);
});
test('unknown cloud model rejected before secret mutation or requests; failed upload stops enrollment',async t=>{
 let calls=0;const{speech,service,secrets,input}=fixture(t,{fetch:async()=>{calls++;return new Response('',{status:403});}});
 assert.throws(()=>speech.configure({mode:'cloud',cloud_enabled:true,cloud_model:'unknown',api_key:'test-key'}),/不支持/);assert.equal(secrets.has(),false);
 speech.configure({mode:'cloud',cloud_enabled:true,api_key:'test-key'});assert.throws(()=>speech.request({...input,model_id:'unknown'}),/不支持/);
 const result=speech.request({...input,model_id:'qwen-audio-3.0-tts-plus'});await finish(speech);assert.equal(service.store.get(result.block_id).body.status,'failed');assert.equal(calls,1);
});
for(const model of require('../desktop/cloud-models.cjs').CLOUD_MODELS.filter(m=>m.family==='minimax'))test(`MiniMax clone, hex WAV and separate model cache: ${model.id}`,async t=>{
 let clones=0,synths=0;const {speech,service,input}=fixture(t,{fetch:async(url,options)=>{
 if(url.includes('getPolicy')){assert.equal(new URL(url).searchParams.get('model'),model.id);return Response.json({data:{upload_dir:'tests',upload_host:'https://test.aliyuncs.com/',oss_access_key_id:'upload-id',signature:'signature',policy:'policy',x_oss_object_acl:'private',x_oss_forbid_overwrite:'true'}});}
 if(options.body instanceof FormData)return new Response('');
 const b=JSON.parse(options.body);assert.equal(b.model,model.id);
 if(b.input.action==='voice_clone'){clones++;assert.match(b.input.audio_url,/^oss:/);assert.match(b.input.voice_id,/^sayagain/);return Response.json({output:{base_resp:{status_code:0}}});}
 synths++;assert.equal(b.input.audio_setting.format,'wav');assert.equal(b.input.output_format,'hex');return Response.json({output:{base_resp:{status_code:0},data:{audio:wav(1).toString('hex'),status:2}}});
 }});speech.configure({mode:'cloud',cloud_enabled:true,api_key:'test-key'});const result=speech.request({...input,model_id:model.id,set_default_model:true});await finish(speech);assert.equal(speech.status().cloud_model,model.id);assert.equal(service.store.get(result.block_id).body.status,'succeeded');assert.equal(clones,1);assert.equal(synths,1);assert(speech.request(input).cached);
});
test('realtime model enrolls matching voice and stores completed WAV',async t=>{
 const id='qwen3-tts-vc-realtime-2026-01-15';const{speech,service,input}=fixture(t,{fetch:async(url,options)=>{assert.equal(JSON.parse(options.body).input.target_model,id);return Response.json({output:{voice:'realtime-voice'}});},realtime:async opts=>{assert.equal(opts.model,id);assert.equal(opts.voice,'realtime-voice');return wav(1);}});speech.configure({mode:'cloud',cloud_enabled:true,api_key:'test-key'});const job=speech.request({...input,model_id:id});await finish(speech);assert.equal(service.store.get(job.block_id).body.status,'succeeded');
});


test('local runtime model identity and revision separate cached audio',async t=>{
 let runs=0;
 const runtime={model_id:'Qwen/Qwen3-TTS-12Hz-1.7B-Base',revision:'local-test-large',device:'cuda:0',model_path:'unused',python:'unused'};
 const {speech,service,input}=fixture(t,{localStatus:()=>({installed:true,space_ok:true,runtime}),localRunner:async request=>{runs++;fs.writeFileSync(request.output_path,wav(1));}});
 const first=speech.request(input);await finish(speech);
 assert.equal(service.store.get(first.block_id).body.status,'succeeded');
 assert.equal(service.store.get(first.block_id).body.model_id,runtime.model_id);
 assert.equal(speech.request(input).cached,true);assert.equal(runs,1);
 runtime.model_id='Qwen/Qwen3-TTS-12Hz-0.6B-Base';runtime.revision='local-test-small';
 const second=speech.request(input);await finish(speech);
 assert.notEqual(first.block_id,second.block_id);assert.equal(runs,2);
 assert.equal(service.store.get(first.block_id).body.model_id,'Qwen/Qwen3-TTS-12Hz-1.7B-Base');
});
