const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {Service}=require('../desktop/service.cjs');
const {Speech,CLOUD_MODEL,BASE}=require('../desktop/speech.cjs');
const {createSecrets}=require('../desktop/secrets.cjs');
function wav(seconds=10,rate=24000){const b=Buffer.alloc(44+seconds*rate*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(b.length-44,40);return b;}
function fixture(t,options={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'sayagain-speech-'));const service=new Service(path.join(root,'data'));let key='';const secrets={has:()=>!!key,get:()=>key,set:v=>{key=v;},clear:()=>{key='';}};const speech=new Speech(service,root,{secrets,localStatus:()=>({space_ok:false,installed:false,reason:'磁盘空间不足'}),...options});t.after(async()=>{await speech.close();service.close();fs.rmSync(root,{recursive:true,force:true});});service.saveSettings({revision:service.config().body.revision,native_language:'zh-CN',target_language:'en-US'});const expression=service.addExpression({original:'I very like it.',improved:'I really like it.',explanation:'测试'});const voice=service.saveVoice({name:'模拟声音',note:'仅测试'});service.addSample({voice_id:voice.block_id,language:'en-US',transcript:'Test sample',bytes:wav(),media_type:'audio/wav',duration_ms:10000,waveform:Array(64).fill(0),source:'import'});return{root,service,speech,secrets,input:{expression_id:expression.block_id,voice_id:voice.block_id,cloud_consent:true}};}
async function finish(speech){await new Promise(resolve=>setImmediate(resolve));await speech.drain();while(speech.busy)await new Promise(resolve=>setTimeout(resolve,5));}
test('insufficient disk blocks local work; cloud needs explicit enable and per-generation consent',async t=>{let calls=0;const {speech,input}=fixture(t,{fetch:async()=>{calls++;throw Error('unexpected');}});assert.throws(()=>speech.request(input),/空间不足/);assert.throws(()=>speech.configure({mode:'cloud',cloud_enabled:false,api_key:'test-key'}),/主动/);assert.equal(speech.status().has_api_key,false);speech.configure({mode:'cloud',cloud_enabled:true,api_key:'test-key'});assert.throws(()=>speech.request({...input,cloud_consent:false}),/确认/);assert.equal(calls,0);assert(!JSON.stringify(speech.status()).includes('test-key'));});
test('cloud enrollment, matching model, saved audio, reuse and no credentials on audio download',async t=>{const calls=[];const {speech,service,input}=fixture(t,{fetch:async(url,options)=>{calls.push({url,options});if(url.endsWith('/customization'))return Response.json({output:{voice:'fake-voice'}});if(url.endsWith('/generation'))return Response.json({output:{audio:{url:'https://test.aliyuncs.com/audio.wav'}}});return new Response(wav(1));}});speech.configure({mode:'cloud',cloud_enabled:true,api_key:'test-only-key'});const result=speech.request(input);await finish(speech);const saved=service.store.get(result.block_id);assert.equal(saved.body.status,'succeeded');assert(fs.existsSync(service.asset(saved.body.asset_id).filename));assert.equal(calls.length,3);assert.equal(calls[0].url,BASE+'/services/audio/tts/customization');assert.equal(JSON.parse(calls[0].options.body).input.target_model,CLOUD_MODEL);assert.equal(JSON.parse(calls[1].options.body).model,CLOUD_MODEL);assert.equal(calls[2].options.headers,undefined);assert.equal(speech.request(input).cached,true);assert.equal(calls.length,3);const e=service.addExpression({original:'Explain me.',improved:'Please explain this to me.',explanation:'测试'});speech.request({...input,expression_id:e.block_id});await finish(speech);assert.equal(calls.filter(c=>c.url.endsWith('/customization')).length,1);assert.equal(calls.length,5);});
test('provider failure never becomes success and does not persist response secrets',async t=>{const {speech,service,input}=fixture(t,{fetch:async()=>new Response('private provider response test-only-key',{status:401})});speech.configure({mode:'cloud',cloud_enabled:true,api_key:'test-only-key'});const result=speech.request(input);await finish(speech);assert.equal(service.store.get(result.block_id).body.status,'failed');assert.match(service.store.get(result.block_id).body.error,/401/);assert(!JSON.stringify(service.state()).includes('test-only-key'));});
test('removing key cancels queued cloud work without network request',async t=>{let calls=0;const {speech,service,input}=fixture(t,{fetch:async()=>{calls++;throw Error('unexpected');}});speech.configure({mode:'cloud',cloud_enabled:true,api_key:'test-only-key'});const result=speech.request(input);speech.clearKey();await finish(speech);assert.equal(service.store.get(result.block_id).body.status,'cancelled');assert.equal(calls,0);assert.equal(speech.status().has_api_key,false);});
test('plaintext key persists and reopens without keychain; permissions and clear',t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'sayagain-plain-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const secrets=createSecrets(root),file=path.join(root,'qianwen-api-key.secret');secrets.set('test-only-plaintext-key');assert.equal(fs.readFileSync(file,'utf8'),'test-only-plaintext-key');assert.equal(fs.statSync(file).mode&0o777,0o600);assert.equal(createSecrets(root).get(),'test-only-plaintext-key');assert.equal(secrets.status().usable,true);assert.throws(()=>secrets.set('bad key'),/格式/);assert.equal(secrets.get(),'test-only-plaintext-key');secrets.clear();assert.equal(secrets.status().present,false);});
test('legacy ciphertext can be replaced without decryption; status does not disclose keys',t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'sayagain-legacy-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const legacy=path.join(root,'qianwen-api-key.enc');fs.writeFileSync(legacy,'unreadable-ciphertext');const secrets=createSecrets(root);assert.equal(secrets.has(),false);assert.match(secrets.status().error,/重新粘贴/);assert.throws(()=>secrets.get(),/重新粘贴/);secrets.set('replacement-test-key');assert.equal(secrets.get(),'replacement-test-key');assert(!JSON.stringify(secrets.status()).includes('replacement-test-key'));secrets.clear();assert.equal(fs.existsSync(legacy),false);});
