const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {TextReview,endpoint}=require('../desktop/text-review.cjs');
function setup(t,fetcher){const root=fs.mkdtempSync(path.join(os.tmpdir(),'text-providers-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return new TextReview(root,fetcher);}
test('provider keys remain isolated; blank preserves same service; endpoint changes require a new key',t=>{const r=setup(t);r.configure({provider:'custom',url:'https://model.service-inference.ai/v1',model:'example',key:'service-key'});assert.throws(()=>r.configure({provider:'qianwen',url:'https://maas.qianwenaiapi.com/compatible-mode/v1',model:'example'}),/API Key/);r.configure({provider:'qianwen',url:'https://maas.qianwenaiapi.com/compatible-mode/v1',model:'example',key:'qwen-key'});r.configure({provider:'custom',url:'https://model.service-inference.ai/v1',model:'another',protocol:'responses'});assert.equal(r.read().key,'service-key');assert(!JSON.stringify(r.status()).includes('service-key'));assert(!JSON.stringify(r.status()).includes('qwen-key'));assert.throws(()=>r.configure({provider:'custom',url:'https://other.test/v1',model:'example'}),/重新填写/);r.clear({provider:'custom'});assert.equal(r.status().has_key,false);assert.equal(r.status().profiles.qianwen.has_key,true);});
test('connection check uses GET models and unsaved configuration; responses generation parses output',async t=>{const calls=[],fields={improved:'Hello.',translation:'你好',explanation:'说明',category:'自然',pattern:''};const r=setup(t,async(url,options)=>{calls.push({url,options});return Response.json(url.endsWith('/models')?{data:[{id:'example'}]}:{output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(fields)}]}]});});const config={provider:'custom',url:'https://model.service-inference.ai/v1',model:'example',protocol:'responses',key:'test-key'};assert.deepEqual(await r.models(config),{models:['example']});assert.equal(r.status().has_key,false);assert.equal(calls[0].options.body,undefined);r.configure(config);assert.deepEqual(await r.improve({text:'Hello',consent:true}),fields);assert.equal(calls[1].url,'https://model.service-inference.ai/v1/responses');assert(JSON.parse(calls[1].options.body).input);assert.equal(calls[1].options.redirect,'error');});
test('legacy configuration migrates and private LAN URLs work while unsafe URLs fail',t=>{const r=setup(t);fs.writeFileSync(r.filename,JSON.stringify({url:'https://old.test/v1/chat/completions',model:'legacy',key:'old-secret'}));assert.equal(r.read().model,'legacy');r.configure({url:'https://old.test/v1',model:'updated'});assert.equal(r.read().key,'old-secret');assert.equal(endpoint('http://192.168.100.101:8000/v1'),'http://192.168.100.101:8000/v1/chat/completions');for(const url of ['http://example.com/v1','https://user:pass@example.com/v1','https://example.com/v1?secret=x'])assert.throws(()=>endpoint(url));});
test('legacy Qwen text profiles retain isolated keys but cannot generate text after TTS correction',async t=>{
 const calls=[],fields={improved:'Hello.',translation:'你好',explanation:'说明',category:'自然',pattern:''};
 const fetcher=async(url,options)=>{calls.push({url,key:options.headers.Authorization});return Response.json(url.endsWith('/models')?{data:[{id:'qwen-b'}]}:{choices:[{message:{content:JSON.stringify(fields)}}]});};
 const r=setup(t,fetcher),url='https://maas.qianwenaiapi.com/compatible-mode/v1',id='qianwen:12345678-1234-1234-1234-123456789abc';
 r.configure({provider:'qianwen',url,model:'qwen-a',key:'secret-a',name:'工作'});
 assert.throws(()=>r.configure({provider:id,url,model:'qwen-b',name:'个人'}),/API Key/);
 r.configure({provider:id,url,model:'qwen-b',key:'secret-b',name:'个人'});
 const reopened=new TextReview(path.dirname(r.filename),fetcher);assert.equal(reopened.status().provider,id);
 await assert.rejects(()=>reopened.improve({text:'Hello',consent:true}),/TTS/);assert.equal(calls.length,0);
 await reopened.models({provider:'qianwen',url,model:'qwen-a'});assert.equal(calls.at(-1).key,'Bearer secret-a');
 reopened.configure({provider:'qianwen',url,model:'qwen-a',name:'工作改名'});await assert.rejects(()=>reopened.improve({text:'Hello',consent:true}),/TTS/);assert.equal(reopened.read().key,'secret-a');
 assert.equal(reopened.status().profiles[id].name,'个人');assert(!JSON.stringify(reopened.status()).includes('secret-'));
 reopened.clear({provider:id});assert.equal(reopened.read().key,'secret-a');assert.equal(reopened.status().profiles[id],undefined);
 reopened.clear({provider:'qianwen'});await assert.rejects(()=>reopened.improve({text:'Hello',consent:true}),/TTS|配置/);
});
