window.inferenceKeys=(()=>{
 const api=window.sayagain,esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 async function open(){
  let config=await api.inferenceKeysStatus(),dialog;
  const render=()=>{dialog.querySelector('[data-ak-groups]').innerHTML=[['manager','管理 AK',config.managers],['usage','使用 AK',config.usages]].map(([kind,label,rows])=>`<section><h3>${label}</h3><p>${kind==='manager'?'验证组织，用于管理与费用查询。':'每个使用 AK 必须匹配一个管理 AK，用于模型调用。'}</p>${rows.map(p=>`<div class="model-notice" data-ak-id="${esc(p.id)}" data-ak-kind="${kind}"><strong>${esc(p.name)}${config.active===p.id?' · 默认使用':''}</strong><p>${kind==='manager'?`组织：${esc(p.organizationId)}`:`匹配：${esc(config.managers.find(m=>m.id===p.managerId)?.name||'待绑定')} · ${p.models?.length||0} 个模型`}</p><div class="form-actions"><button type="button" class="button" data-ak-action="edit">编辑${kind==='usage'?' / 匹配':''}</button><button type="button" class="button" data-ak-action="enable">${p.enabled?'停用':'启用'}</button>${kind==='usage'?'<button type="button" class="button" data-ak-action="select">设为默认使用</button><button type="button" class="button" data-ak-action="report">查询绑定组织费用</button>':''}<button type="button" class="button quiet" data-ak-action="delete">删除</button></div></div>`).join('')||'<p>尚未配置</p>'}<button type="button" class="button" data-ak-add="${kind}">＋ 添加${label}</button></section>`).join('');};
  async function edit(kind,p={}){await window.itemEditor({title:kind==='manager'?'管理 AK · 验证组织':'使用 AK · 匹配管理 AK',message:kind==='manager'?'保存时调用 /manage/whoami 验证组织。':'保存时验证使用 AK 的模型列表。绑定由你选择，请选择属于该使用 AK 的管理组织；不代表服务已自动验证两者归属。',fields:`<label class="field">名称<input name="name" maxlength="80" required value="${esc(p.name)}"></label><label class="field">${kind==='manager'?'管理 AK（sk-mgmt-v1-…）':'使用 AK'}<input name="key" type="password" autocomplete="off" placeholder="${p.id?'已保存，留空保留':'输入完整 AK'}"></label>${kind==='usage'?`<label class="field">匹配管理 AK<select name="managerId" required><option value="">请选择管理 AK</option>${config.managers.filter(m=>m.enabled).map(m=>`<option value="${esc(m.id)}" ${m.id===p.managerId?'selected':''}>${esc(m.name)} · ${esc(m.organizationId)}</option>`).join('')}</select></label>`:''}`,submit:'验证并保存',onSave:async values=>{config=await api.inferenceKeysUpdate({...values,kind,id:p.id,action:'save'});}});render();}
  return window.itemEditor({title:'service-inference · 管理 AK 与使用 AK',message:'先添加管理 AK，再添加并匹配使用 AK。管理 AK 不会用于生成；删除已绑定的管理 AK 前须先改绑。',fields:'<div data-ak-groups></div>',submit:'完成',onSave:async()=>{},onOpen:d=>{dialog=d;render();dialog.querySelector('[data-ak-groups]').onclick=async event=>{const add=event.target.closest('[data-ak-add]'),button=event.target.closest('[data-ak-action]');try{if(add){await edit(add.dataset.akAdd);return;}if(!button)return;const row=button.closest('[data-ak-id]'),kind=row.dataset.akKind,id=row.dataset.akId,p=(kind==='manager'?config.managers:config.usages).find(p=>p.id===id),action=button.dataset.akAction;if(action==='edit'){await edit(kind,p);return;}if(action==='report'){const report=await api.inferenceKeysReport({id});await window.itemEditor({title:'绑定组织费用 · 最近30天',message:`使用 AK：${report.usageName}\n管理 AK：${report.managerName}\n组织：${report.organizationId}\n组织总费用：USD ${report.totalCostUsd}\n这是组织汇总，不是此使用 AK 的单独费用。`,submit:'完成',onSave:async()=>{}});return;}if(action==='delete'){const accepted=await window.itemEditor({title:'删除此 AK？',message:p.name,danger:true,submit:'删除',onSave:async()=>{config=await api.inferenceKeysUpdate({kind,id,action});}});if(!accepted)return;}else config=await api.inferenceKeysUpdate({kind,id,action,enabled:!p.enabled});render();}catch(error){dialog.querySelector('.form-error').textContent=error.message;}};}});
 }
 return{open};
})();
