window.peoplePage=(()=>{
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function render(root,state,refresh){
  const people=state.recording_people||[],picture=(avatar,name)=>avatar?`<img src="${esc(avatar)}" alt="头像">`:esc((name||'新').slice(0,1));
  const card=person=>{const b=person?.body||{},id=person?.block_id||'',avatars=[...new Set([b.avatar,...(b.avatars||[])].filter(Boolean))],refs=(state.recordings||[]).flatMap(s=>(s.body.speaker_profiles||[]).filter(p=>p.person_id===id).map(p=>s.block_id)),color=b.color||window.recordingView.color({body:{speaker_profiles:[{key:'person',person_id:id}]}},'person');
   return `<details class="person-library-card" data-person-card="${esc(id)}" ${id?'':'hidden'}><summary><span class="speaker-avatar">${picture(b.avatar,b.name)}</span><span><strong>${esc(b.name||'新建人物')}</strong><small>${id?`${new Set(refs).size} 个会话 · ${refs.length} 个声音标签`:'保存后可在音频中引用'}</small></span><span class="person-color-dot" data-color-dot="${color}"></span></summary><form data-person-editor="${esc(id)}"><div class="speaker-avatar-editor"><span class="speaker-avatar" data-person-preview>${picture(b.avatar,b.name)}</span><label class="avatar-upload">上传头像<input type="file" data-person-upload accept="image/png,image/jpeg,image/webp" aria-label="人物头像"></label><button type="button" data-person-clear>恢复文字头像</button></div><div class="person-avatar-gallery">${avatars.map((a,i)=>`<button type="button" data-library-avatar="${i}" title="设为默认头像"><img src="${esc(a)}" alt="头像 ${i+1}"></button>`).join('')}</div><label>姓名<input name="name" required maxlength="60" value="${esc(b.name||'')}"></label><label>备注<textarea name="note" maxlength="500">${esc(b.note||'')}</textarea></label><label class="person-color-field">默认波形颜色<input type="color" name="color" value="${color}"></label><small>默认头像和颜色同步到未单独设置的 Speaker；本次独立设置会保留。</small><p data-person-feedback role="status"></p><button class="button" type="submit">${id?'保存人物资料':'创建人物'}</button></form>${id?`<div class="recording-item-actions"><button class="button quiet" data-person-archive="${id}">归档人物</button><button class="button quiet" data-person-merge="${id}">合并到其他人物</button></div>`:''}</details>`;
  };
  root.innerHTML=`<div class="page people-page"><header class="recordings-heading"><div><h1>人物形象</h1><p>管理姓名、头像与默认波形颜色，在不同音频中引用同一个人物。</p></div><button class="button" data-create-person>＋ 新建人物</button></header><input type="search" class="people-search" placeholder="搜索人物姓名或备注" aria-label="搜索人物姓名或备注"><div data-people-timeline></div><div class="people-library">${card(null)}${people.map(card).join('')}</div>${people.length?'':'<p class="muted">还没有人物。新建一个人物，或在音频的说话人卡片中创建并关联。</p>'}</div>`;
  root.querySelectorAll('[data-color-dot]').forEach(el=>el.style.backgroundColor=el.dataset.colorDot);
  root.querySelector('[data-create-person]').onclick=()=>{const el=root.querySelector('[data-person-card=""]');el.hidden=false;el.open=true;el.querySelector('[name=name]').focus();};
  const timeline=window.libraryTimeline.setup(root.querySelector('[data-people-timeline]'),{unit:'位人物',onChange:visible=>{const ids=new Set(visible.map(p=>p.block_id));root.querySelectorAll('[data-person-card]').forEach(el=>{if(el.dataset.personCard)el.hidden=!ids.has(el.dataset.personCard);});const list=root.querySelector('.people-library');visible.forEach(p=>list.append(root.querySelector('[data-person-card="'+p.block_id+'"]')));}});timeline.update(people);
  root.querySelector('.people-search').oninput=e=>{const q=e.target.value.trim().toLocaleLowerCase();timeline.update(people.filter(p=>(p.body.name+' '+p.body.note).toLocaleLowerCase().includes(q)));};
  root.querySelectorAll('[data-person-archive],[data-person-merge]').forEach(button=>button.onclick=async()=>{
   if(!await window.unsaved.permit())return;
   const person=people.find(p=>p.block_id===(button.dataset.personArchive||button.dataset.personMerge));
   const merge=!!button.dataset.personMerge,targets=people.filter(p=>p.block_id!==person.block_id);
   const done=await window.itemEditor({title:merge?'合并重复人物':'归档人物',message:merge?'所有录音引用会转到目标人物，采用目标的姓名和备注，头像集合合并。原人物归档；恢复原人物不会撤销引用迁移。':'历史录音仍保留这个人物，归档后不再出现在新关联的选择列表。',fields:merge?`<label class="field">合并到<select name="target_id" required><option value="">请选择</option>${targets.map(p=>`<option value="${p.block_id}">${esc(p.body.name)}</option>`).join('')}</select></label>`:'',submit:merge?'合并并归档原人物':'归档',onSave:values=>window.sayagain.managePerson({id:person.block_id,revision:person.body.revision,action:merge?'merge':'archive',...values,target_revision:targets.find(p=>p.block_id===values.target_id)?.body.revision})});
   if(done)await refresh();
  });
  root.querySelectorAll('[data-person-editor]').forEach(form=>{
   const person=people.find(p=>p.block_id===form.dataset.personEditor),avatars=[...new Set([person?.body.avatar,...(person?.body.avatars||[])].filter(Boolean))],preview=form.querySelector('[data-person-preview]'),feedback=form.querySelector('[data-person-feedback]'),submit=form.querySelector('[type=submit]');
   const setAvatar=avatar=>{form.dataset.avatar=avatar;window.unsaved.mark(form);preview.innerHTML=picture(avatar,form.elements.name.value);feedback.textContent='预览已更新，保存后应用。';};
   form.querySelector('[data-person-clear]').onclick=()=>setAvatar('');
   form.querySelectorAll('[data-library-avatar]').forEach(button=>button.onclick=()=>setAvatar(avatars[Number(button.dataset.libraryAvatar)]));
   form.querySelector('[data-person-upload]').onchange=async e=>{const file=e.target.files[0];if(!file)return;submit.disabled=true;try{const avatar=await window.recordingPage.cropAvatar(file);if(avatar)setAvatar(avatar);}catch(error){feedback.textContent=error.message;}finally{submit.disabled=false;e.target.value='';}};
   form.onsubmit=async e=>{e.preventDefault();submit.disabled=true;try{await window.sayagain.saveRecordingPerson({id:person?.block_id,revision:person?.body.revision,name:form.elements.name.value,note:form.elements.note.value,color:form.elements.color.value,...(form.dataset.avatar!==undefined?{avatar:form.dataset.avatar}:{})});window.unsaved.clear(form);await refresh();}catch(error){feedback.textContent=error.message;submit.disabled=false;}};
  });
 }
 return{render};
})();
