window.recordingPage=(()=>{
 const api=window.sayagain;let root,sessionId=null,busy=false,stream,context,processor,source,parts=[],frames=0,offset=0,started=0,queue=Promise.resolve(),pending=0,failed=[],stopping=false;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const status=text=>{const el=root?.querySelector('#recording-status');if(el)el.textContent=text;};
 async function reload(){const state=await api.state();render(root,state);}
 function render(container,state){
  root=container;if(busy)return;
  const sessions=state.recordings||[];if(!sessions.some(s=>s.block_id===sessionId))sessionId=sessions[0]?.block_id||null;
  const clips=(state.recording_clips||[]).filter(c=>c.body.recording_id===sessionId).sort((a,b)=>a.body.sequence-b.body.sequence);
  root.innerHTML=`<div class="page recordings-page"><h1>我的录音</h1><p class="muted">一次会话可包含多个文件或连续录音。录音每30秒保存一段，原始音频与文字分开保留。</p><div class="recording-toolbar"><input id="recording-title" maxlength="120" placeholder="新录音名称"><button class="button" id="recording-create">新建会话</button><select id="recording-session" aria-label="录音会话">${sessions.map(s=>`<option value="${s.block_id}" ${s.block_id===sessionId?'selected':''}>${esc(s.body.title)} · ${s.body.clip_count} 段</option>`).join('')}</select></div><div class="recording-toolbar"><button class="button primary" id="recording-start" ${!sessionId?'disabled':''}>开始录音</button><button class="button" id="recording-stop" disabled>停止并保存</button><button class="button" id="recording-import" ${!sessionId?'disabled':''}>导入录音文件</button><input type="file" id="recording-files" accept="audio/*" multiple hidden><button class="button" id="recording-retry" ${failed.length?'':'hidden'}>重试未保存片段 (${failed.length})</button></div><p id="recording-status" role="status">${failed.length?'有未保存片段，请重试后再离开。':'录音仅保存在本机。导入文件会转换为PCM WAV，每30秒分段。单文件上限100MB。'}</p>${sessionId?`<small class="muted">会话 block_id：${sessionId}</small>`:''}<div class="recording-toolbar"><button class="button" id="recording-speakers" ${!sessionId?'disabled':''}>区分说话人（实验）</button><input id="recording-keywords" placeholder="关键词，用逗号分隔" aria-label="检测关键词" value="${esc((sessions.find(s=>s.block_id===sessionId)?.body.keyword_analysis?.keywords||[]).join(', '))}"><button class="button" id="recording-detect" ${!sessionId?'disabled':''}>检测关键词</button></div><p class="muted">说话人仅为本次会话的候选分组，重叠发言或短语音可能不准确。关键词按声音检测，结果需核对。</p><div id="recording-clips">${clips.map(c=>`<section class="recording-clip"><strong>${c.body.sequence+1}. ${esc(c.body.source_name)}</strong><small>${(c.body.source_offset_ms/1000).toFixed(1)}s 起 · ${(c.body.duration_ms/1000).toFixed(1)}s · ${c.body.captured_at?'录制 '+new Date(c.body.captured_at).toLocaleString():'导入 '+new Date(c.body.imported_at).toLocaleString()}</small><audio controls preload="none" src="sayagain-asset://audio/${c.body.asset_id}"></audio>${analysisView(c)}<label>转写 / 笔记（可人工修正）<textarea data-transcript="${c.block_id}">${esc(c.body.transcript)}</textarea></label><button class="button" data-save-transcript="${c.block_id}" data-revision="${c.body.revision}">保存文字</button><button class="button" data-transcribe="${c.block_id}">本地转写</button></section>`).join('')||'<p class="muted">先新建会话，再录音或导入文件。</p>'}</div><section class="settings-section"><h2>录音模型</h2><div id="recording-models">正在检查本机登记…</div><button class="button" id="recording-model-refresh">刷新模型状态</button><p class="muted">模型下载由 Skill 执行；文件存在不代表推理已验证。关键词和说话人分析需要手动点击启动，结果仅供核对。</p></section></div>`;
  root.querySelector('#recording-create').onclick=async()=>{try{sessionId=(await api.createRecording({title:root.querySelector('#recording-title').value||'录音 '+new Date().toLocaleString()})).block_id;await reload();}catch(e){status(e.message);}};
  root.querySelector('#recording-session').onchange=async e=>{sessionId=e.target.value;await reload();};
  root.querySelector('#recording-start').onclick=()=>start().catch(e=>{cleanup();busy=false;status(e.message);lock(false);});
  root.querySelector('#recording-stop').onclick=()=>stop();
  root.querySelector('#recording-import').onclick=()=>root.querySelector('#recording-files').click();
  root.querySelector('#recording-files').onchange=e=>importFiles([...e.target.files]);
  root.querySelector('#recording-retry').onclick=async()=>{busy=true;lock(true);const retry=failed;failed=[];for(const input of retry)enqueue(input);await queue;busy=false;await reload();};
  root.querySelectorAll('[data-save-transcript]').forEach(b=>b.onclick=async()=>{try{await api.updateRecordingTranscript({id:b.dataset.saveTranscript,revision:Number(b.dataset.revision),text:root.querySelector(`[data-transcript="${b.dataset.saveTranscript}"]`).value});await reload();}catch(e){status(e.message);}});
  root.querySelectorAll('[data-transcribe]').forEach(b=>b.onclick=async()=>{b.disabled=true;status('正在本地转写…');try{await api.transcribeRecording({id:b.dataset.transcribe});await reload();status('转写已保存，请核对识别结果。');}catch(e){status(e.message);b.disabled=false;}});
  root.querySelector('#recording-speakers').onclick=()=>analyze('speakers');
  root.querySelector('#recording-detect').onclick=()=>analyze('keywords');
  root.querySelector('#recording-model-refresh').onclick=models;models();
 }
 async function models(){try{const rows=await api.recordingModels();const el=root?.querySelector('#recording-models');if(el)el.innerHTML=rows.map(m=>`<p><strong>${esc(m.name)}</strong> · ${esc(m.status)}${m.device?' · '+esc(m.device):''}</p>`).join('');}catch(e){status(e.message);}}
 async function analyze(mode){busy=true;lock(true);status('正在本地分析，请稍候…');try{await api.analyzeRecording({id:sessionId,mode,keywords:root.querySelector('#recording-keywords').value});busy=false;await reload();status('分析结果已保存，请核对。');}catch(e){busy=false;lock(false);status(e.message);}}
 function analysisView(c){const b=c.body;return (b.speaker_analysis?'<p>候选说话人：'+(b.speaker_analysis.segments.map(s=>`${(s.start_ms/1000).toFixed(1)}–${(s.end_ms/1000).toFixed(1)}s ${esc(s.speaker||"不确定")}`).join('；')||'未发现可分组的语音')+'</p>':'')+(b.keyword_analysis?'<p>关键词：'+(b.keyword_analysis.segments.map(s=>esc(s.keyword)).join('、')||'未检出')+'</p>':'');}
 function lock(value){root.querySelectorAll('#recording-create,#recording-session,#recording-start,#recording-import,#recording-speakers,#recording-detect').forEach(el=>el.disabled=value);root.querySelector('#recording-stop').disabled=!stream;}
 function pcm(samples,rate){const bytes=new Uint8Array(44+samples.length*2),v=new DataView(bytes.buffer);const str=(p,t)=>[...t].forEach((c,i)=>v.setUint8(p+i,c.charCodeAt(0)));str(0,'RIFF');v.setUint32(4,bytes.length-8,true);str(8,'WAVEfmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,rate,true);v.setUint32(28,rate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);str(36,'data');v.setUint32(40,bytes.length-44,true);samples.forEach((s,i)=>v.setInt16(44+i*2,Math.max(-32768,Math.min(32767,Math.round(s*32767))),true));return bytes;}
 function enqueue(input){pending++;queue=queue.then(async()=>{try{await api.addRecordingClip(input);status('片段已保存 · '+new Date().toLocaleTimeString());}catch(e){failed.push(input);status('保存失败：'+e.message);if(stream&&!stopping)setTimeout(stop,0);}finally{pending--;}});}
 function flush(){if(!frames)return;const samples=new Float32Array(frames);let at=0;parts.forEach(p=>{samples.set(p,at);at+=p.length;});const rate=context.sampleRate;enqueue({recording_id:sessionId,client_id:crypto.randomUUID(),source:'microphone',source_name:'连续录音',source_offset_ms:offset,captured_at:started+offset,bytes:pcm(samples,rate)});offset+=frames/rate*1000;frames=0;parts=[];}
 async function start(){if(failed.length)throw Error('请先重试未保存片段');busy=true;lock(true);stream=await navigator.mediaDevices.getUserMedia({audio:true});context=new AudioContext();await context.resume();source=context.createMediaStreamSource(stream);processor=context.createScriptProcessor(4096,1,1);parts=[];frames=0;offset=0;started=Date.now();stopping=false;processor.onaudioprocess=e=>{if(stopping)return;const samples=e.inputBuffer.getChannelData(0).slice();parts.push(samples);frames+=samples.length;status('正在录音 · '+Math.floor((offset+frames/context.sampleRate*1000)/1000)+' 秒');if(frames>=context.sampleRate*30)flush();if(pending>=3){status('保存速度不足，正在停止录音以保护未保存数据');stop();}};source.connect(processor);processor.connect(context.destination);lock(true);}
 function cleanup(){processor?.disconnect();source?.disconnect();stream?.getTracks().forEach(t=>t.stop());context?.close();processor=source=stream=context=null;}
 async function stop(){if(stopping)return;stopping=true;flush();cleanup();await queue;busy=false;stopping=false;await reload();}
 async function importFiles(files){if(failed.length){status('请先重试未保存片段');return;}busy=true;lock(true);let error='';try{for(const file of files){if(file.size>100*1024*1024)throw Error(file.name+' 超过100MB');const ctx=new AudioContext();let audio;try{audio=await ctx.decodeAudioData(await file.arrayBuffer());}finally{await ctx.close();}for(let start=0;start<audio.length;start+=audio.sampleRate*30){const end=Math.min(audio.length,start+audio.sampleRate*30),mono=new Float32Array(end-start);for(let c=0;c<audio.numberOfChannels;c++){const data=audio.getChannelData(c);for(let i=start;i<end;i++)mono[i-start]+=data[i]/audio.numberOfChannels;}enqueue({recording_id:sessionId,client_id:crypto.randomUUID(),source:'import',source_name:file.name,source_offset_ms:start/audio.sampleRate*1000,bytes:pcm(mono,audio.sampleRate)});await queue;if(failed.length)throw Error('有片段未保存，已暂停导入，请重试该片段后重新选择未导入文件。');}}}catch(e){error=e.message;}await queue;busy=false;await reload();if(error)status(error);}
 document.addEventListener('click',e=>{if((busy||failed.length)&&e.target.closest('[data-page]')){e.stopImmediatePropagation();e.preventDefault();status('请先停止录音并保存未完成片段。');}},true);
 window.addEventListener('beforeunload',e=>{if(busy||failed.length){e.preventDefault();e.returnValue='';}});
 return{render,get busy(){return busy;}};
})();
