let clipBuffer=null, clipSource=null, trimStart=0, trimEnd=0, liveContext=null, liveFrame=null;
const clipTime=s=>`${Math.floor(s/60)}:${(s%60).toFixed(1).padStart(4,'0')}`;
function recorderMarkup(language) {
 const text=readingPrompts[language.split('-')[0]], label=labelLanguage(language);
 return `<div class="reading-prompt"><div class="reading-heading"><span>${icon('messages')} 母语朗读 · ${escapeHtml(label)}</span><span>参考文案</span></div>${text?`<p dir="auto">${escapeHtml(text)}</p><button type="button" class="button quiet" data-action="use-reading">我将朗读这段文案</button>`:'<p>这个母语暂时没有预置文案。请用母语自然讲述一次日常经历，并在下方填写原文。</p>'}<small>用平时说话的语气，清晰读完。建议 10–30 秒；不要配乐。</small></div>
 <div class="record-studio"><div class="studio-caption"><span id="record-status" role="status">准备好时，开始说话</span><span id="live-time">0:00</span></div><svg id="live-wave" viewBox="0 0 480 80" aria-label="麦克风实时波形" role="img">${Array.from({length:60},(_,i)=>`<line x1="${i*8+4}" x2="${i*8+4}" y1="38" y2="42"/>`).join('')}</svg><div class="record-controls"><button type="button" class="button primary" data-action="record" id="record-button">开始录音</button><button type="button" class="button quiet" data-action="import-audio" id="import-button">${icon('upload')} 导入音频</button><input id="audio-file" type="file" hidden accept="audio/wav,audio/x-wav,audio/mpeg,audio/mp4,audio/x-m4a,audio/ogg,audio/webm,.wav,.mp3,.m4a,.ogg,.webm"></div></div>
 <div id="clip-editor" hidden><div class="clip-heading"><span>试听与裁剪</span><button type="button" class="button quiet" data-action="reset-trim">恢复全段</button></div><svg id="clip-wave" viewBox="0 0 512 80" role="img" aria-label="录音波形，深色部分为保留片段"></svg><div class="trim-controls"><label>起点 <output id="trim-start-value"></output><input id="trim-start" type="range" min="0" step="0.01" aria-label="裁剪起点"></label><label>终点 <output id="trim-end-value"></output><input id="trim-end" type="range" min="0" step="0.01" aria-label="裁剪终点"></label></div><div class="clip-playback"><button type="button" class="icon-button" data-action="preview-clip" id="preview-clip" aria-label="试听选段">${icon('play')}</button><span id="clip-play-time">0:00</span><span id="clip-length"></span></div><p class="form-hint">拖动起止位置去掉开头、结尾的空白。保存仅保留选段，原文件不变。若裁掉朗读内容，请同步修改下方原文。</p></div><audio id="audio-preview" hidden></audio>`;
}
function stopLiveWave(){cancelAnimationFrame(liveFrame);liveFrame=null;if(liveContext){liveContext.close().catch(()=>{});liveContext=null;}}
async function startLiveWave(stream){stopLiveWave();liveContext=new AudioContext();const context=liveContext;await context.resume();if(context!==liveContext)return;const analyser=context.createAnalyser();analyser.fftSize=2048;context.createMediaStreamSource(stream).connect(analyser);const values=new Uint8Array(analyser.fftSize);const draw=()=>{if(context!==liveContext)return;analyser.getByteTimeDomainData(values);document.querySelectorAll('#live-wave line').forEach((line,i)=>{let peak=0;for(let j=i*34;j<Math.min(values.length,(i+1)*34);j++)peak=Math.max(peak,Math.abs(values[j]-128)/128);const h=Math.max(2,Math.min(36,peak*72));line.setAttribute('y1',40-h);line.setAttribute('y2',40+h);});liveFrame=requestAnimationFrame(draw);};draw();}
function resetClip(){stopLiveWave();clipBuffer=null;clipSource=null;trimStart=0;trimEnd=0;}
function clipPeaks(buffer,start=0,end=buffer.length){const values=buffer.getChannelData(0);const peaks=Array.from({length:64},(_,i)=>{const a=Math.floor(start+(end-start)*i/64),b=Math.floor(start+(end-start)*(i+1)/64);let max=0;for(let j=a;j<b;j+=Math.max(1,Math.floor((b-a)/1500)))max=Math.max(max,Math.abs(values[j]));return max;});const max=Math.max(...peaks,.01);return peaks.map(v=>v/max);}
function buildClip(){if(!clipBuffer)return;const a=Math.floor(trimStart*clipBuffer.sampleRate),b=Math.min(clipBuffer.length,Math.ceil(trimEnd*clipBuffer.sampleRate));const clip={length:b-a,sampleRate:clipBuffer.sampleRate,numberOfChannels:clipBuffer.numberOfChannels,getChannelData:c=>clipBuffer.getChannelData(c).subarray(a,b)};const wav=encodeWav(clip);if(wav.length>25*1024*1024)throw Error('选段超过 25 MB，请缩短后保存');pendingAudio={bytes:wav,media_type:'audio/wav',duration_ms:clip.length/clip.sampleRate*1000,waveform:clipPeaks(clip),source:clipSource};}
function updateTrim(which){if(!clipBuffer)return;const min=Math.min(.1,clipBuffer.duration);if(which==='trim-start')trimStart=Math.min(Number($('#trim-start').value),trimEnd-min);else if(which==='trim-end')trimEnd=Math.max(Number($('#trim-end').value),trimStart+min);$('#trim-start').value=trimStart;$('#trim-end').value=trimEnd;$('#trim-start-value').textContent=clipTime(trimStart);$('#trim-end-value').textContent=clipTime(trimEnd);$('#clip-length').textContent=`保留 ${(trimEnd-trimStart).toFixed(1)} 秒`;document.querySelectorAll('#clip-wave line').forEach((line,i)=>line.classList.toggle('outside',i/64<trimStart/clipBuffer.duration||i/64>=trimEnd/clipBuffer.duration));const audio=$('#audio-preview');audio.pause();audio.currentTime=trimStart;$('#clip-play-time').textContent=clipTime(trimStart);$('#audio-info').textContent=trimEnd-trimStart<10?'选段短于 10 秒，可保存；Qwen 云端克隆需要至少 10 秒。':'选段已准备好，可试听后保存。';}
function setupClip(decoded,source){$('.record-studio').classList.add('has-clip');$('#record-status').textContent=source==='import'?'已导入音频':'录音已停止';clipBuffer=decoded;clipSource=source;trimStart=0;trimEnd=decoded.duration;buildClip();if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(new Blob([pendingAudio.bytes],{type:'audio/wav'}));const audio=$('#audio-preview');audio.src=previewUrl;audio.onplay=()=>{$('#preview-clip').innerHTML=icon('pause');$('#preview-clip').setAttribute('aria-label','暂停试听');};audio.onpause=()=>{$('#preview-clip').innerHTML=icon('play');$('#preview-clip').setAttribute('aria-label','试听选段');};audio.ontimeupdate=()=>{if(audio.currentTime>=trimEnd){audio.pause();audio.currentTime=trimStart;}$('#clip-play-time').textContent=clipTime(audio.currentTime);};$('#clip-wave').innerHTML=clipPeaks(decoded).map((v,i)=>`<line x1="${i*8+4}" x2="${i*8+4}" y1="${40-Math.max(2,v*34)}" y2="${40+Math.max(2,v*34)}"/>`).join('');$('#trim-start').max=decoded.duration;$('#trim-end').max=decoded.duration;$('#clip-editor').hidden=false;updateTrim();$('#save-editor').disabled=false;}
