window.workflows=(()=>{
 const api=window.sayagain,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const field=(name,label,value='',extra='')=>`<label class="field">${label}<textarea name="${name}" ${extra}>${esc(value)}</textarea></label>`;
 let current,refresh,selectedText='',selectedClip='';
 document.addEventListener('selectionchange',()=>{const selection=getSelection();const node=selection?.anchorNode?.parentElement?.closest('[data-clip]');const clip=node?.dataset.clip||selection?.anchorNode?.parentElement?.closest('.recording-clip')?.querySelector('[data-transcript]')?.dataset.transcript;if(clip&&selection.toString().trim()){selectedClip=clip;selectedText=selection.toString().trim();}});
 async function textSettings(){
  let config=await api.textReviewStatus(),ak=await api.inferenceKeysStatus();
  return window.itemEditor({title:'大模型 API · 表达优化',message:'此处用于表达优化。千问 TTS 账号请在设置页的「Qwen 云端 · 音色克隆与语音生成」中管理。保存不调用模型。',fields:`<label class="field">服务<select name="provider">${Object.entries(config.profiles).filter(([id])=>!id.startsWith('qianwen')).map(([id,p])=>`<option value="${esc(id)}" ${config.provider===id?'selected':''}>${esc(p.label)}</option>`).join('')}</select></label><label class="field">Base URL 或完整接口地址<input name="url" type="url" required></label><label class="field">接口类型<select name="protocol"><option value="chat">Chat Completions</option><option value="responses">Responses</option></select></label><label class="field">模型名称<input name="model" list="text-model-options" required maxlength="160"><datalist id="text-model-options"></datalist></label><div data-inference-binding hidden><label class="field">使用 AK（已匹配管理 AK）<select name="usage_id"></select></label><button type="button" class="button" data-manage-ak>管理 AK / 使用 AK 配置</button></div><label class="field" data-single-key>API Key<input name="key" type="password" autocomplete="off"></label><div class="form-actions"><button type="button" class="button" data-model-test>读取模型 / 测试连接</button><button type="button" class="button quiet" data-clear-provider>清除此服务配置</button></div><p class="form-hint" data-model-status>读取模型不发送业务文字，不代表模型生成已验证。</p>`,onSave:values=>api.configureTextReview(values),onOpen:dialog=>{
   const form=dialog.querySelector('form'),status=dialog.querySelector('[data-model-status]');
   function syncOptions(selected){form.elements.provider.innerHTML=Object.entries(config.profiles).filter(([id])=>!id.startsWith('qianwen')).map(([id,p])=>`<option value="${esc(id)}">${esc(p.label)}</option>`).join('');form.elements.provider.value=config.profiles[selected]?selected:'service-inference';}
   function fill(){const si=form.elements.provider.value==='service-inference';dialog.querySelector('[data-inference-binding]').hidden=!si;dialog.querySelector('[data-single-key]').hidden=si;form.elements.key.disabled=si;form.elements.usage_id.disabled=!si;form.elements.url.readOnly=si;const p=config.profiles[form.elements.provider.value];form.elements.usage_id.innerHTML='<option value="">请选择已匹配的使用 AK</option>'+ak.usages.filter(u=>u.enabled&&ak.managers.some(m=>m.id===u.managerId&&m.enabled)).map(u=>`<option value="${esc(u.id)}">${esc(u.name)} → ${esc(ak.managers.find(m=>m.id===u.managerId)?.name)}</option>`).join('');form.elements.usage_id.value=p.usage_id||ak.active||'';for(const name of ['url','model','protocol'])form.elements[name].value=p[name]||'';form.elements.key.value='';form.elements.key.placeholder=p.has_key?'已保存，留空保持；更换地址须重新填写':'填写此服务的 Key';dialog.querySelector('datalist').replaceChildren();status.textContent='填写或读取模型后保存，即用于后续表达优化。';}
   if(!form.elements.provider.value)form.elements.provider.value='service-inference';form.elements.provider.onchange=fill;fill();
   dialog.querySelector('[data-manage-ak]').onclick=async()=>{await window.inferenceKeys.open();ak=await api.inferenceKeysStatus();config=await api.textReviewStatus();syncOptions(form.elements.provider.value);fill();};
   dialog.querySelector('[data-model-test]').onclick=async e=>{const button=e.currentTarget;button.disabled=true;try{const result=await api.textReviewModels(Object.fromEntries(new FormData(form)));dialog.querySelector('datalist').innerHTML=result.models.map(id=>`<option value="${esc(id)}"></option>`).join('');status.textContent=`连接成功，读取 ${result.models.length} 个模型。请选择文本模型；当前输入尚未保存。`;}catch(error){status.textContent=error.message;}finally{button.disabled=false;}};
   dialog.querySelector('[data-clear-provider]').onclick=async()=>{if(!confirm('删除当前这组配置的地址、模型和 Key？其他配置会保留。'))return;try{const removed=form.elements.provider.value;config=await api.clearTextReview({provider:removed});syncOptions(removed);fill();status.textContent='已清除。';}catch(error){status.textContent=error.message;}};
  }});
 }

 async function improveClip(id){
  const state=await api.state(),clip=state.recording_clips.find(c=>c.block_id===id);if(!clip)throw Error('录音片段不存在');
  const text=selectedClip===id&&clip.body.transcript.includes(selectedText)?selectedText:clip.body.transcript;if(!text)throw Error('请先完成转写');
  let config=await api.textReviewStatus();
  await window.itemEditor({title:'从录音整理表达',message:'可选取转写中的一句话。原音频留在本地；只有点击生成时，将此处原句发送到配置的文本服务。建议可编辑，保存后关联原录音。',fields:`${field('original','所选原句',text,'required maxlength="10000"')}<label class="field">原文语言<input name="language" required value="${esc(state.config.body.target_language)}" placeholder="en-US、zh-CN 等"></label><div class="form-actions"><button class="button" type="button" data-text-settings>配置文本服务</button><button class="button" type="button" data-generate-improvement>生成优化建议</button></div><p data-text-provider>${esc(config.url||'尚未配置，可手工整理建议')}</p><label class="checkbox"><input type="checkbox" name="consent">允许本次发送所选原句到上述服务，可能产生费用</label>${field('improved','优化后的表达','','required maxlength="10000"')}${field('translation','译文')}${field('explanation','修改原因')}<label class="field">类别<input name="category" value="自然表达" required></label>${field('pattern','可复用句型')}`,onSave:values=>api.expressionFromClip({...values,clip_id:id,clip_revision:clip.body.revision}),onOpen:dialog=>{
   dialog.querySelector('[data-text-settings]').onclick=async()=>{await textSettings();config=await api.textReviewStatus();dialog.querySelector('[data-text-provider]').textContent=config.url;dialog.querySelector('[name=consent]').checked=false;};
   dialog.querySelector('[data-generate-improvement]').onclick=async e=>{e.currentTarget.disabled=true;const button=e.currentTarget;try{const result=await api.improveText({text:dialog.querySelector('[name=original]').value,native_language:state.config.body.native_language,consent:dialog.querySelector('[name=consent]').checked});for(const key of ['improved','translation','explanation','category','pattern'])dialog.querySelector(`[name=${key}]`).value=result[key];dialog.querySelector('.form-error').textContent='建议已生成，请核对后保存';}catch(error){dialog.querySelector('.form-error').textContent=error.message;}finally{button.disabled=false;}};
  }});await refresh();
 }
 async function exportDialog(kind,entries){if(!entries.length)throw Error('没有可导出的记录');const formats=kind==='expressions'?['json','csv','md']:kind==='recordings'?['txt','srt','vtt']:['audio'];let dialogRef;await window.itemEditor({title:'导出所选内容',message:kind==='recordings'?'字幕按原音频来源分别生成，保留时间范围。':'选择需要导出的内容；随后选择本机保存位置。',fields:`<label class="field">格式<select name="format">${formats.map(f=>`<option>${f}</option>`).join('')}</select></label><div class="selection-list">${entries.map(e=>`<label class="checkbox"><input type="checkbox" data-export-id="${e.block_id}" checked>${esc(e.body.title||e.body.original||e.body.transcript||e.body.text_snapshot||e.body.source_name||e.block_id)}</label>`).join('')}</div>`,onOpen:d=>dialogRef=d,onSave:async values=>{const ids=[...dialogRef.querySelectorAll('[data-export-id]:checked')].map(el=>el.dataset.exportId);const result=await api.exportItems({kind,ids,format:values.format});if(result)await window.itemEditor({title:'导出完成',message:`${result.count} 个文件已保存到 ${result.directory}`,submit:'完成',onSave:async()=>{}});}});}
 async function batch(entries,restore=false){
  if(!entries.length)throw Error('当前列表没有可整理内容');if(!await window.unsaved.permit())return;let dialogRef;
  const done=await window.itemEditor({title:restore?'批量恢复':'批量归档',message:'按所选记录逐条处理；冲突或失败的条目会单独报告。',fields:`<label class="checkbox"><input type="checkbox" data-select-all checked>全选</label><div class="selection-list">${entries.map(e=>`<label class="checkbox"><input type="checkbox" data-batch-id="${e.block_id}" checked>${esc(e.body.title||e.body.name||e.body.original||e.body.transcript||e.body.source_name||e.block_id)}</label>`).join('')}</div>`,submit:restore?'恢复所选':'归档所选',onOpen:d=>{dialogRef=d;d.querySelector('[data-select-all]').onchange=e=>d.querySelectorAll('[data-batch-id]').forEach(box=>box.checked=e.target.checked);},onSave:async()=>{
   const ids=[...dialogRef.querySelectorAll('[data-batch-id]:checked')].map(el=>el.dataset.batchId);if(!ids.length)throw Error('请至少选择一条');const errors=[];let completed=0;
   const order={recording:0,voice:0,recording_person:0,expression:0,voice_sample:1,recording_clip:1};
   for(const entry of entries.filter(e=>ids.includes(e.block_id)).sort((a,b)=>order[a.body.type]-order[b.body.type]))try{const fresh=await api.state(),record=[...fresh.expressions,...fresh.voices,...fresh.samples,...fresh.recordings,...fresh.recording_clips,...fresh.recording_people,...fresh.archived_items].find(r=>r.block_id===entry.block_id);if(!record)throw Error('记录不存在');const input={id:record.block_id,revision:record.body.revision};if(restore)await api.archiveItem({...input,action:'restore'});else switch(record.body.type){case 'expression':if(record.body.status!=='active')throw Error('已归档');await api.editExpression({...input,action:'archive'});break;case 'voice':await api.archiveVoice(input);break;case 'voice_sample':await api.editSample({...input,action:'archive'});break;case 'recording_person':await api.managePerson({...input,action:'archive'});break;default:await api.editRecording({...input,action:'archive',kind:record.body.type==='recording_clip'?'clip':undefined});}completed++;dialogRef.querySelector(`[data-batch-id="${entry.block_id}"]`).checked=false;}catch(error){errors.push((entry.body.title||entry.body.name||entry.body.original||entry.block_id)+': '+error.message);}
   if(errors.length)throw Error(`已完成 ${completed} 条，未完成：\n${errors.join('\n')}`);
  }});if(done)await refresh();
 }
 function decorate(root,state,page,callback){current=state;refresh=callback;
  const header=root.querySelector('.page-heading,.recordings-heading');if(!header)return;
  const bar=document.createElement('div');bar.className='workflow-toolbar';header.after(bar);
  function add(label,fn){const b=document.createElement('button');b.className='button quiet';b.textContent=label;b.onclick=()=>Promise.resolve().then(fn).catch(e=>window.itemEditor({title:'未完成',message:e.message,submit:'知道了',onSave:async()=>{}}));bar.append(b);}
  const visible=(selector,attribute,items)=>[...root.querySelectorAll(selector)].filter(el=>!el.hidden&&!el.closest('[hidden]')).map(el=>items.find(r=>r.block_id===el.getAttribute(attribute))).filter(Boolean);
  if(page==='review'){add('批量归档',()=>batch(visible('[data-entry]','data-entry',state.expressions).filter(e=>e.body.status==='active')));add('导出表达',()=>exportDialog('expressions',visible('[data-entry]','data-entry',state.expressions)));}
  if(page==='recordings'){add('批量归档',()=>batch(root.querySelector('[data-recording-open]')?visible('[data-recording-open]','data-recording-open',state.recordings):visible('[data-transcript]','data-transcript',state.recording_clips)));add('导出文字 / 字幕',()=>exportDialog('recordings',root.querySelector('[data-session-edit]')?[state.recordings.find(s=>s.block_id===root.querySelector('[data-session-edit]').dataset.sessionEdit)].filter(Boolean):state.recordings));add('导出音频',()=>exportDialog('audio',visible('[data-transcript]','data-transcript',state.recording_clips)));}
  if(page==='voices'){add('批量归档样本',()=>batch(visible('[data-sample]','data-sample',state.samples)));add('导出音频',()=>exportDialog('audio',visible('[data-sample]','data-sample',state.samples)));}
  if(page==='people')add('批量归档人物',()=>batch(visible('[data-person-card]','data-person-card',state.recording_people)));
  if(page==='archive')add('批量恢复',()=>batch(state.archived_items,true));
  if(page==='settings'){add('大模型 API 配置',textSettings);add('service-inference AK 管理',()=>window.inferenceKeys.open());}
 }
 document.addEventListener('click',async e=>{const exportButton=e.target.closest('[data-export-audio]');if(exportButton){const s=await api.state(),entry=[...s.samples,...s.syntheses,...s.recording_clips,...s.recording_sources].find(r=>r.block_id===exportButton.dataset.exportAudio);try{await exportDialog('audio',entry?[entry]:[]);}catch(error){await window.itemEditor({title:'导出未完成',message:error.message,submit:'知道了',onSave:async()=>{}});}return;}const b=e.target.closest('[data-improve-clip]');if(b)improveClip(b.dataset.improveClip).catch(error=>window.itemEditor({title:'无法优化表达',message:error.message,submit:'知道了',onSave:async()=>{}}));});
 return{decorate,textSettings,exportDialog};
})();
