const { _electron: electron } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { setTimeout: delay } = require('node:timers/promises');
const root = path.resolve(__dirname,'..');
const temporary = fs.mkdtempSync(path.join(os.tmpdir(),'sayagain-ui-'));
const output = path.join(root,'test-results');fs.mkdirSync(output,{recursive:true});
let app;
const errors=[];
async function launch() {
 app=await electron.launch({args:[root,'--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream'],env:{...process.env,SAYAGAIN_DATA_DIR:temporary},timeout:60000});
 const page=await app.firstWindow();page.on('pageerror',error=>errors.push(error.message));await page.waitForSelector('#main .page');return page;
}
(async()=>{
 let page=await launch();
 await page.locator('#language-form [name="native_language"]').fill('zh-CN');await page.locator('#language-form [name="target_language"]').fill('en-US');await page.locator('#language-form button[type="submit"]').click();
 await page.waitForSelector('[data-action="example"]');await page.locator('[data-action="example"]').click();await page.locator('#save-editor').click();await page.waitForSelector('.entry');
 assert.equal(await page.locator('.improved').textContent(),'I really like this idea.');
 await page.locator('[data-action="favorite"]').click();await page.waitForSelector('[data-action="favorite"][aria-pressed="true"]');
 await page.locator('#search').fill('no-such-expression');assert.equal(await page.locator('.entry').count(),0);await page.locator('#search').fill('');
 const second={original:'Can you explain me this part?',improved:'Could you explain this part to me?',translation:'可以给我解释一下这部分吗？',explanation:'explain 的内容放在动词后面，用 to 引出听者。Could you 也让请求更委婉。',pattern:'Could you explain + 内容 + to me?',category:'grammar'};
 await page.locator('.page-heading [data-action="add-expression"]').click();for(const [key,value]of Object.entries(second)){const field=page.locator(`#editor [name="${key}"]`);if(key==='category')await field.selectOption(value);else await field.fill(value);}await page.locator('#save-editor').click();await page.waitForFunction(()=>document.querySelectorAll('.entry').length===2);
 assert.equal(await page.locator('.practice-column').first().evaluate(el=>getComputedStyle(el).borderLeftWidth),'1px');
 await page.locator('#toast').waitFor({state:'hidden'});await page.screenshot({path:path.join(output,'review-desktop.png')});
 await page.locator('[data-page="voices"]').click();await page.locator('.page-heading [data-action="add-voice"]').click();await page.locator('#editor [name="name"]').fill('日常声音');await page.locator('#editor [name="note"]').fill('自动化测试示例，不是真人录音');await page.locator('#save-editor').click();await page.waitForSelector('.voice');
 await page.locator('[data-action="add-sample"]').click();await page.locator('#record-button').click();await page.waitForFunction(()=>document.querySelector('#record-button').textContent==='停止录音');await delay(1800);await page.locator('#record-button').click();await page.waitForFunction(()=>!document.querySelector('#save-editor').disabled);await page.locator('#editor [name="transcript"]').fill('自动化测试音频');await page.locator('#save-editor').click();await page.waitForSelector('.sample');
 await page.locator('[data-action="play"]').click();await page.waitForFunction(()=>document.querySelector('.player-play').getAttribute('aria-label')==='暂停参考录音');
 await page.locator('[data-seek]').click();assert.equal(await page.locator('.waveform').evaluate(el=>getComputedStyle(el).outlineStyle),'none');
 await page.locator('[data-action="speed"]').click();assert.equal(await page.locator('.speed').textContent(),'0.75×');
 await page.locator('[data-action="add-sample"]').click();
 const wav=Buffer.alloc(16044);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(8000,24);wav.writeUInt32LE(16000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(16000,40);for(let i=0;i<8000;i++)wav.writeInt16LE(Math.round(Math.sin(i/8000*440*Math.PI*2)*8000),44+i*2);
 await page.locator('#audio-file').setInputFiles({name:'test-tone.wav',mimeType:'audio/wav',buffer:wav});await page.waitForFunction(()=>!document.querySelector('#save-editor').disabled);await page.locator('#save-editor').click();await page.waitForFunction(()=>document.querySelectorAll('.sample').length===2);
 await page.locator('[data-action="default-sample"]').click();await page.waitForFunction(()=>document.querySelectorAll('.sample-header .tag').length===1);
 await page.locator('[data-action="play"]').first().click();await page.waitForFunction(()=>document.querySelector('.player-play').getAttribute('aria-label')==='暂停参考录音');
 await page.locator('#toast').waitFor({state:'hidden'});await page.screenshot({path:path.join(output,'voices-desktop.png')});
 await page.locator('[data-action="default-voice"]').click();await page.waitForSelector('.voice-title .tag');
 await page.locator('[data-action="archive-voice"]').click();await page.waitForFunction(()=>document.querySelectorAll('.voice').length===0);
 const archived=await page.evaluate(()=>window.sayagain.state());assert.deepEqual(archived.config.body.default_voice_ids,[]);assert.equal(archived.samples.length,2);
 await page.locator('#voice-filter').selectOption('archived');await page.locator('[data-action="archive-voice"]').click();await page.locator('#voice-filter').selectOption('active');await page.waitForSelector('.sample');
 await page.locator('[data-page="settings"]').click();await page.locator('[name="target_language"]').fill('ja-JP');await page.locator('#language-form button').click();await page.waitForFunction(()=>document.querySelector('#language-badge').textContent.includes('ja-JP'));
 await page.locator('#toast').waitFor({state:'hidden'});await page.screenshot({path:path.join(output,'settings-desktop.png')});
 await page.locator('[data-page="review"]').click();assert.equal(await page.locator('.entry').count(),0);await page.locator('#pair-filter').selectOption('all');assert.equal(await page.locator('.entry').count(),2);
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(680,850));await page.waitForFunction(()=>innerWidth===680);
 assert.equal(await page.locator('.practice-column').first().evaluate(el=>getComputedStyle(el).borderLeftWidth),'0px');
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(output,'review-narrow.png')});
 await page.locator('#fullscreen').click();await page.waitForFunction(()=>document.querySelector('#fullscreen').getAttribute('aria-label')==='退出全屏');await page.keyboard.press('Escape');await page.waitForFunction(()=>document.querySelector('#fullscreen').getAttribute('aria-label')==='进入全屏');
 assert.equal(await page.evaluate(()=>typeof window.require),'undefined');
 await app.close();app=null;
 page=await launch();const reopened=await page.evaluate(()=>window.sayagain.state());assert.equal(reopened.config.body.target_language,'ja-JP');assert.equal(reopened.expressions.length,2);assert.equal(reopened.voices.length,1);assert.equal(reopened.samples.length,2);
 await page.locator('[data-page="voices"]').click();await page.locator('[data-action="play"]').first().click();await page.waitForFunction(()=>document.querySelector('.player-play').getAttribute('aria-label')==='暂停参考录音');
 assert.deepEqual(errors,[]);
 console.log('Passed Electron: onboarding, manual expressions, search/favorite, fake-microphone recording, WAV import/default sample, audio playback/seek/speed, archive/restore, settings, responsive layout, fullscreen, context isolation and persistence after relaunch.');
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{if(app)await app.close();fs.rmSync(temporary,{recursive:true,force:true});});
